# Generated by Django 4.2 on 2023-05-01 19:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
