# Generated by Django 4.2 on 2023-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_post_topic_titleprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='LastUpdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
