# Generated by Django 4.2 on 2023-05-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_comment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='LastMessage',
            new_name='author',
        ),
    ]
