# Generated by Django 4.2 on 2023-05-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='answers',
            new_name='viewCounter',
        ),
    ]
