# Generated by Django 4.2 on 2023-05-06 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_carouselimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
