# Generated by Django 4.2 on 2023-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_topic_lastupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_commentable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
