# Generated by Django 4.2 on 2023-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_topic_is_commentable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='is_commentable',
            field=models.BooleanField(default=True),
        ),
    ]
